"""BPSK demodulator with carrier hopping sync and tracking."""

import numpy as np

from ..protocol.constants import (
    SAMPLE_RATE,
    SAMPLES_PER_SYMBOL,
    PREAMBLE_SYMBOLS,
)
from ..protocol.melody import HopScheduler, HOP_SEQUENCE_HZ
from ..protocol.frame import RxFrameParser
from .agc import AGC
from .timing import GardnerTimingRecovery


def _build_reference_preamble() -> np.ndarray:
    """Build a reference preamble waveform using the same method as the modulator."""
    from .modulator import PSKModulator
    # Preamble is alternating 1,0,1,0...
    preamble_bits = [1 if i % 2 == 0 else 0 for i in range(PREAMBLE_SYMBOLS)]
    mod = PSKModulator()
    return mod.modulate(preamble_bits)


class PSKDemodulator:
    """BPSK demodulator with Among Us Drip hop tracking.

    Strategy: cross-correlate with a reference preamble to find exact frame
    start, then demodulate with a continuous-phase LO locked to the hop
    schedule.
    """

    def __init__(self, energy_threshold: float = 0.1):
        self.energy_threshold = energy_threshold
        self._ref_preamble = _build_reference_preamble()

    def demodulate(self, audio: np.ndarray) -> str:
        """Demodulate a complete audio buffer to text."""
        # Phase 1: Find exact frame start
        offset = self._find_frame_start(audio)
        if offset < 0:
            return ""

        sig = audio[offset:]
        if len(sig) < SAMPLES_PER_SYMBOL * 2:
            return ""

        # Phase 2: Demodulate with continuous-phase LO
        scheduler = HopScheduler()
        scheduler.reset(0)
        n_symbols = len(sig) // SAMPLES_PER_SYMBOL

        # Pre-build LO phases for vectorized IQ computation
        lo_theta = 0.0
        frame_parser = RxFrameParser()
        prev_phase = 0.0

        for sym in range(n_symbols):
            freq = scheduler.current_freq
            s0 = sym * SAMPLES_PER_SYMBOL
            s1 = s0 + SAMPLES_PER_SYMBOL
            chunk = sig[s0:s1]

            # Vectorized IQ downconversion
            phase_inc = 2.0 * np.pi * freq / SAMPLE_RATE
            phases = lo_theta + phase_inc * np.arange(1, SAMPLES_PER_SYMBOL + 1)
            lo_theta = phases[-1]

            i_val = np.mean(chunk * np.cos(phases))
            q_val = np.mean(chunk * (-np.sin(phases)))

            phase = np.arctan2(q_val, i_val)

            # Differential decode
            delta = phase - prev_phase
            delta = (delta + np.pi) % (2 * np.pi) - np.pi
            bit = 1 if abs(delta) > np.pi / 2 else 0

            prev_phase = phase
            scheduler.advance_symbol()

            frame_parser.feed_bit(bit)
            if frame_parser.is_idle():
                break

        return frame_parser.decoded_text

    def _find_frame_start(self, audio: np.ndarray) -> int:
        """Find the exact sample offset where the TX frame begins.

        Uses cross-correlation with a reference preamble generated by the
        actual modulator (including pulse shaping and normalization).
        """
        ref = self._ref_preamble
        ref_len = len(ref)

        if len(audio) < ref_len:
            return -1

        # Search first half of audio for the preamble
        search_len = min(len(audio), max(len(audio) // 2, ref_len * 2))

        # Use FFT-based correlation for speed on long signals
        n_fft = 1
        while n_fft < search_len + ref_len:
            n_fft *= 2

        audio_pad = np.zeros(n_fft)
        audio_pad[:search_len] = audio[:search_len]
        ref_pad = np.zeros(n_fft)
        ref_pad[:ref_len] = ref[::-1]  # time-reversed for correlation

        corr = np.fft.irfft(np.fft.rfft(audio_pad) * np.fft.rfft(ref_pad))
        # Valid correlation region
        corr = np.abs(corr[ref_len - 1:search_len])

        peak = np.argmax(corr)
        if corr[peak] < self.energy_threshold:
            return -1

        return int(peak)
